// apps/lemon-brains/src/app/components/question-options/question-options.component.ts
import { CommonModule } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';
import {
  LearningOption,
  LearningQuestion,
  OptionDisplay,
} from '@knowledge-quest/learning';

@Component({
  selector: 'app-question-options',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './question-options.component.html',
  styleUrl: './question-options.component.scss',
})
export class QuestionOptionsComponent {
  @Input({ required: true }) question!: LearningQuestion;
  @Input() selectedAnswer: string | number | null = null;
  @Input() wrongAnswer: string | number | null = null;
  @Output() optionSelected = new EventEmitter<string | number>();

  get optionDisplay(): OptionDisplay {
    return this.question.optionDisplay;
  }

  trackByValue(_index: number, option: LearningOption): string | number {
    return option.value;
  }

  onSelect(option: LearningOption): void {
    if (this.selectedAnswer !== null) {
      return;
    }
    this.optionSelected.emit(option.value);
  }
}

<div class="options">
  <button
    *ngFor="let option of question.options; trackBy: trackByValue"
    type="button"
    (click)="onSelect(option)"
    [class.selected]="selectedAnswer === option.value"
    [class.wrong]="wrongAnswer === option.value"
    [disabled]="selectedAnswer !== null"
    [ngClass]="{
      'color-option': optionDisplay === 'colorSwatch',
      'shape-option': optionDisplay === 'shapeSvg',
      'emoji-option': optionDisplay === 'emoji'
    }"
    [style.background-color]="
      optionDisplay === 'colorSwatch' ? option.colorHex : null
    "
  >
    <span *ngIf="optionDisplay === 'text'">{{ option.label }}</span>
    <span *ngIf="optionDisplay === 'emoji'" class="emoji-label">{{
      option.label
    }}</span>
    <svg *ngIf="optionDisplay === 'shapeSvg'" viewBox="0 0 100 100">
      <path
        [attr.d]="option.svgPath"
        [attr.fill]="option.fillColor"
        stroke="#333"
        stroke-width="2"
      ></path>
    </svg>
  </button>
</div>

// apps/fairy-tale-kingdom/src/learning/QuestionOptions.tsx
import type { LearningOption, LearningQuestion } from '@knowledge-quest/learning';

interface QuestionOptionsProps {
  question: LearningQuestion;
  wrongValue?: string | number | null;
  locked?: boolean;
  onSelect: (option: LearningOption) => void;
}

export function QuestionOptions({
  question,
  wrongValue = null,
  locked = false,
  onSelect,
}: QuestionOptionsProps) {
  return (
    <div className={`question-options display-${question.optionDisplay}`}>
      {question.options.map((option) => (
        <button
          key={String(option.value)}
          type="button"
          className={[
            'question-option',
            question.optionDisplay === 'colorSwatch' ? 'color-option' : '',
            question.optionDisplay === 'shapeSvg' ? 'shape-option' : '',
            question.optionDisplay === 'emoji' ? 'emoji-option' : '',
            wrongValue === option.value ? 'wrong' : '',
          ]
            .filter(Boolean)
            .join(' ')}
          style={
            question.optionDisplay === 'colorSwatch' && option.colorHex
              ? { backgroundColor: option.colorHex }
              : undefined
          }
          disabled={locked}
          onClick={() => onSelect(option)}
        >
          {question.optionDisplay === 'text' && <span>{option.label}</span>}
          {question.optionDisplay === 'emoji' && (
            <span className="emoji-label">{option.label}</span>
          )}
          {question.optionDisplay === 'shapeSvg' && (
            <svg viewBox="0 0 100 100" aria-hidden="true">
              <path
                d={option.svgPath}
                fill={option.fillColor ?? '#ccc'}
                stroke="#333"
                strokeWidth="2"
              />
            </svg>
          )}
          {question.optionDisplay === 'colorSwatch' && (
            <span className="sr-only">
              {option.label ?? String(option.value)}
            </span>
          )}
        </button>
      ))}
    </div>
  );
}
